# Generated by Django 3.2.4 on 2022-02-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_MOdel_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=10)),
                ('pdf_document', models.FileField(upload_to=None)),
                ('date', models.DateField()),
                ('discription', models.CharField(max_length=150)),
            ],
        ),
    ]
