# Generated by Django 3.2.4 on 2022-02-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_model_class',
            name='pdf_document',
            field=models.FileField(upload_to='pdf_doc'),
        ),
    ]
