# Generated by Django 3.2.4 on 2022-02-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_subject_model_class_pdf_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_model_class',
            name='pdf_document',
            field=models.FileField(upload_to='media/pdf_doc'),
        ),
    ]
