# Generated by Django 3.2.4 on 2022-02-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_subject_model_class_pdf_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_model_class',
            name='userhid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
